"""empty message

Revision ID: 532d3a2aef97
Revises: 5d625152dc7b
Create Date: 2019-10-07 14:45:20.760609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '532d3a2aef97'
down_revision = '5d625152dc7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('hudai', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business', 'hudai')
    # ### end Alembic commands ###
