"""empty message

Revision ID: 5d625152dc7b
Revises: bcd30a2827a2
Create Date: 2019-10-07 14:32:32.860766

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5d625152dc7b'
down_revision = 'bcd30a2827a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_merchant',
    sa.Column('id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('business_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('role', mysql.TINYINT(unsigned=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['merchant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('business_merchant')
    # ### end Alembic commands ###
