"""empty message

Revision ID: 7969a5d78d9c
Revises: 471c509d08dd
Create Date: 2019-10-07 14:27:14.883553

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7969a5d78d9c'
down_revision = '471c509d08dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_merchant', sa.Column('dddd', mysql.BIGINT(unsigned=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business_merchant', 'dddd')
    # ### end Alembic commands ###
