"""empty message

Revision ID: a2e2193573cb
Revises: a4abe23d81ec
Create Date: 2019-10-07 14:46:04.804249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2e2193573cb'
down_revision = 'a4abe23d81ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('api_endpoint', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business', 'api_endpoint')
    # ### end Alembic commands ###
