"""empty message

Revision ID: a4abe23d81ec
Revises: 532d3a2aef97
Create Date: 2019-10-07 14:45:33.962277

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a4abe23d81ec'
down_revision = '532d3a2aef97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business', 'hudai')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('hudai', mysql.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###
