"""empty message

Revision ID: bcd30a2827a2
Revises: 7969a5d78d9c
Create Date: 2019-10-07 14:27:31.368733

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bcd30a2827a2'
down_revision = '7969a5d78d9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business_merchant', 'dddd')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_merchant', sa.Column('dddd', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
