"""empty message

Revision ID: f7b5f17499a5
Revises: c8b34e27f33e
Create Date: 2019-10-07 13:06:53.059564

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f7b5f17499a5'
down_revision = 'c8b34e27f33e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business',
    sa.Column('id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('owner_name', sa.String(length=255), nullable=True),
    sa.Column('billing_address', sa.Text(), nullable=True),
    sa.Column('geo_lat', sa.Float(), nullable=True),
    sa.Column('geo_long', sa.Float(), nullable=True),
    sa.Column('billing_phone', sa.String(length=20), nullable=True),
    sa.Column('billing_email', sa.String(length=127), nullable=True),
    sa.Column('logo_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('cover_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('open_time', sa.Time(), nullable=True),
    sa.Column('close_time', sa.Time(), nullable=True),
    sa.Column('bot_app_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('bot_url', sa.String(length=127), nullable=True),
    sa.Column('page_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('page_url', sa.String(length=127), nullable=True),
    sa.Column('inserted_on', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_on', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('business_merchant',
    sa.Column('id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('business_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('role', mysql.TINYINT(unsigned=True), nullable=True),
    sa.PrimaryKeyConstraint('id', 'business_id')
    )
    op.drop_table('business_model')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_model',
    sa.Column('id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('owner_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('billing_address', mysql.TEXT(), nullable=True),
    sa.Column('geo_lat', mysql.FLOAT(), nullable=True),
    sa.Column('geo_long', mysql.FLOAT(), nullable=True),
    sa.Column('billing_phone', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('billing_email', mysql.VARCHAR(length=127), nullable=True),
    sa.Column('logo_id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('cover_id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('open_time', mysql.TIME(), nullable=True),
    sa.Column('close_time', mysql.TIME(), nullable=True),
    sa.Column('bot_app_id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('bot_url', mysql.VARCHAR(length=127), nullable=True),
    sa.Column('page_id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('page_url', mysql.VARCHAR(length=127), nullable=True),
    sa.Column('inserted_on', mysql.TIMESTAMP(), nullable=True),
    sa.Column('updated_on', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.drop_table('business_merchant')
    op.drop_table('business')
    # ### end Alembic commands ###
